spring.application.name=backend

#Datasource Configuration
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.url=jdbc:postgresql://localhost:5432/achive
spring.datasource.username=postgres
spring.datasource.password=rootroot

#Datasource spring SQL init
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql

#Mybatis mapper location
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/**/**.xml

#Logging level => DEBUG
#logging.level.org.springframework.boot.autoconfigure=DEBUG
#logging.level.org.mybatis=DEBUG
#logging.level.archive.backend=DEBUG
#logging.level.archive.backend.domain.news.service.impl.NewsDAO=DEBUG

#spring security admin login
spring.security.user.name=admin
spring.security.user.password=1234

#naver news API account
naver.client.id=${NAVER_CLIENT_ID}
naver.client.secret=${NAVER_CLIENT_SECRET}