spring.application.name=backend

#Datasource Configuration
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.url=jdbc:postgresql://localhost:5432/achive
spring.datasource.username=postgres
spring.datasource.password=rootroot

#Datasource spring SQL init
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql

#Spring Security user
spring.security.user.name=user
spring.security.user.password=1234